name: Nova
version: ${project.version}
authors: [ "StudioCode", "ByteZ1337", "Javahase" ]
website: "https://github.com/xenondevs/Nova/"
main: xyz.xenondevs.nova.Nova
api-version: 1.18

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:${kotlin.version}
  - org.jetbrains.kotlin:kotlin-reflect:${kotlin.version}
  - org.jetbrains.exposed:exposed-core:${exposed.version}
  - org.jetbrains.exposed:exposed-dao:${exposed.version}
  - org.jetbrains.exposed:exposed-jdbc:${exposed.version}
  - org.jetbrains:annotations:${annotations.version}
  - com.zaxxer:HikariCP:${hikaricp.version}
  - xyz.xenondevs:particle:${particlelib.version}
  - me.xdrop:fuzzywuzzy:${fuzzywuzzy.version}
  - net.lingala.zip4j:zip4j:${zip4j.version}

softdepend:
  - WorldGuard
  - GriefPrevention
  - PlotSquared
  - GriefDefender
  - ProtectionStones
  - Vault
  - ItemsAdder
  - Towny
  - Oraxen
  - MMOItems
  - AuthMe

permissions:
  nova.command.*:
    description: Gives access to all Nova commands.
    children:
      - nova.command.give
      - nova.command.debug
      - nova.command.items
      - nova.command.render_distance
      - nova.command.nvrecipe
      - nova.command.nvusage
      - nova.command.modeldata
  nova.command.give:
    description: Allows players to cheat nova items using /nova give.
  nova.command.debug:
    description: Allows the usage of the /nova debug command.
  nova.command.items:
    description: Allows players to open the nova items menu.
    default: true
  nova.command.renderDistance:
    description: Allows players to configure their armor stand render distance.
    default: true
  nova.command.nvrecipe:
    description: Allows players to use the /nvrecipe command.
    default: true
  nova.command.nvusage:
    description: Allows players to use the /nvusage command.
    default: true
  nova.misc.updateReminder:
    description: Players with this permission will be reminded if a new version is available
  nova.misc.bypassTileEntityLimits:
    description: Players with this permission will be able to bypass the tile entity limits set in the config.
  nova.command.modeldata:
    description: Allows players to use the /nvmodeldata command.