package xyz.xenondevs.nova.registry.vanilla

import net.minecraft.core.registries.Registries
import xyz.xenondevs.nova.registry.vanilla.VanillaRegistryAccess.registryOrThrow

object VanillaRegistries {
    
    val ACTIVITY = registryOrThrow(Registries.ACTIVITY)
    val ATTRIBUTE = registryOrThrow(Registries.ATTRIBUTE)
    val BANNER_PATTERN = registryOrThrow(Registries.BANNER_PATTERN)
    val BIOME = registryOrThrow(Registries.BIOME)
    val BIOME_SOURCE = registryOrThrow(Registries.BIOME_SOURCE)
    val BLOCK = registryOrThrow(Registries.BLOCK)
    val BLOCK_ENTITY_TYPE = registryOrThrow(Registries.BLOCK_ENTITY_TYPE)
    val BLOCK_PREDICATE_TYPE = registryOrThrow(Registries.BLOCK_PREDICATE_TYPE)
    val BLOCK_STATE_PROVIDER_TYPE = registryOrThrow(Registries.BLOCK_STATE_PROVIDER_TYPE)
    val CARVER = registryOrThrow(Registries.CARVER)
    val CAT_VARIANT = registryOrThrow(Registries.CAT_VARIANT)
    val CHAT_TYPE = registryOrThrow(Registries.CHAT_TYPE)
    val CHUNK_GENERATOR = registryOrThrow(Registries.CHUNK_GENERATOR)
    val CHUNK_STATUS = registryOrThrow(Registries.CHUNK_STATUS)
    val COMMAND_ARGUMENT_TYPE = registryOrThrow(Registries.COMMAND_ARGUMENT_TYPE)
    val CONFIGURED_CARVER = registryOrThrow(Registries.CONFIGURED_CARVER)
    val CONFIGURED_FEATURE = registryOrThrow(Registries.CONFIGURED_FEATURE)
    val CUSTOM_STAT = registryOrThrow(Registries.CUSTOM_STAT)
    val DAMAGE_TYPE = registryOrThrow(Registries.DAMAGE_TYPE)
    val DECORATED_POT_PATTERNS = registryOrThrow(Registries.DECORATED_POT_PATTERNS)
    val DENSITY_FUNCTION = registryOrThrow(Registries.DENSITY_FUNCTION)
    val DENSITY_FUNCTION_TYPE = registryOrThrow(Registries.DENSITY_FUNCTION_TYPE)
    val DIMENSION = registryOrThrow(Registries.DIMENSION)
    val DIMENSION_TYPE = registryOrThrow(Registries.DIMENSION_TYPE)
    val ENCHANTMENT = registryOrThrow(Registries.ENCHANTMENT)
    val ENTITY_TYPE = registryOrThrow(Registries.ENTITY_TYPE)
    val FEATURE = registryOrThrow(Registries.FEATURE)
    val FEATURE_SIZE_TYPE = registryOrThrow(Registries.FEATURE_SIZE_TYPE)
    val FLAT_LEVEL_GENERATOR_PRESET = registryOrThrow(Registries.FLAT_LEVEL_GENERATOR_PRESET)
    val FLOAT_PROVIDER_TYPE = registryOrThrow(Registries.FLOAT_PROVIDER_TYPE)
    val FLUID = registryOrThrow(Registries.FLUID)
    val FOLIAGE_PLACER_TYPE = registryOrThrow(Registries.FOLIAGE_PLACER_TYPE)
    val FROG_VARIANT = registryOrThrow(Registries.FROG_VARIANT)
    val GAME_EVENT = registryOrThrow(Registries.GAME_EVENT)
    val HEIGHT_PROVIDER_TYPE = registryOrThrow(Registries.HEIGHT_PROVIDER_TYPE)
    val INSTRUMENT = registryOrThrow(Registries.INSTRUMENT)
    val INT_PROVIDER_TYPE = registryOrThrow(Registries.INT_PROVIDER_TYPE)
    val ITEM = registryOrThrow(Registries.ITEM)
    val LEVEL_STEM = registryOrThrow(Registries.LEVEL_STEM)
    val LOOT_CONDITION_TYPE = registryOrThrow(Registries.LOOT_CONDITION_TYPE)
    val LOOT_FUNCTION_TYPE = registryOrThrow(Registries.LOOT_FUNCTION_TYPE)
    val LOOT_NBT_PROVIDER_TYPE = registryOrThrow(Registries.LOOT_NBT_PROVIDER_TYPE)
    val LOOT_NUMBER_PROVIDER_TYPE = registryOrThrow(Registries.LOOT_NUMBER_PROVIDER_TYPE)
    val LOOT_POOL_ENTRY_TYPE = registryOrThrow(Registries.LOOT_POOL_ENTRY_TYPE)
    val LOOT_SCORE_PROVIDER_TYPE = registryOrThrow(Registries.LOOT_SCORE_PROVIDER_TYPE)
    val MATERIAL_CONDITION = registryOrThrow(Registries.MATERIAL_CONDITION)
    val MATERIAL_RULE = registryOrThrow(Registries.MATERIAL_RULE)
    val MEMORY_MODULE_TYPE = registryOrThrow(Registries.MEMORY_MODULE_TYPE)
    val MENU = registryOrThrow(Registries.MENU)
    val MOB_EFFECT = registryOrThrow(Registries.MOB_EFFECT)
    val MULTI_NOISE_BIOME_SOURCE_PARAMETER_LIST = registryOrThrow(Registries.MULTI_NOISE_BIOME_SOURCE_PARAMETER_LIST)
    val NOISE = registryOrThrow(Registries.NOISE)
    val NOISE_SETTINGS = registryOrThrow(Registries.NOISE_SETTINGS)
    val PAINTING_VARIANT = registryOrThrow(Registries.PAINTING_VARIANT)
    val PARTICLE_TYPE = registryOrThrow(Registries.PARTICLE_TYPE)
    val PLACED_FEATURE = registryOrThrow(Registries.PLACED_FEATURE)
    val PLACEMENT_MODIFIER_TYPE = registryOrThrow(Registries.PLACEMENT_MODIFIER_TYPE)
    val POINT_OF_INTEREST_TYPE = registryOrThrow(Registries.POINT_OF_INTEREST_TYPE)
    val POSITION_SOURCE_TYPE = registryOrThrow(Registries.POSITION_SOURCE_TYPE)
    val POS_RULE_TEST = registryOrThrow(Registries.POS_RULE_TEST)
    val POTION = registryOrThrow(Registries.POTION)
    val PROCESSOR_LIST = registryOrThrow(Registries.PROCESSOR_LIST)
    val RECIPE_SERIALIZER = registryOrThrow(Registries.RECIPE_SERIALIZER)
    val RECIPE_TYPE = registryOrThrow(Registries.RECIPE_TYPE)
    val ROOT_PLACER_TYPE = registryOrThrow(Registries.ROOT_PLACER_TYPE)
    val RULE_TEST = registryOrThrow(Registries.RULE_TEST)
    val SCHEDULE = registryOrThrow(Registries.SCHEDULE)
    val SENSOR_TYPE = registryOrThrow(Registries.SENSOR_TYPE)
    val SOUND_EVENT = registryOrThrow(Registries.SOUND_EVENT)
    val STAT_TYPE = registryOrThrow(Registries.STAT_TYPE)
    val STRUCTURE = registryOrThrow(Registries.STRUCTURE)
    val STRUCTURE_PIECE = registryOrThrow(Registries.STRUCTURE_PIECE)
    val STRUCTURE_PLACEMENT = registryOrThrow(Registries.STRUCTURE_PLACEMENT)
    val STRUCTURE_POOL_ELEMENT = registryOrThrow(Registries.STRUCTURE_POOL_ELEMENT)
    val STRUCTURE_PROCESSOR = registryOrThrow(Registries.STRUCTURE_PROCESSOR)
    val STRUCTURE_SET = registryOrThrow(Registries.STRUCTURE_SET)
    val STRUCTURE_TYPE = registryOrThrow(Registries.STRUCTURE_TYPE)
    val TEMPLATE_POOL = registryOrThrow(Registries.TEMPLATE_POOL)
    val TREE_DECORATOR_TYPE = registryOrThrow(Registries.TREE_DECORATOR_TYPE)
    val TRIM_MATERIAL = registryOrThrow(Registries.TRIM_MATERIAL)
    val TRIM_PATTERN = registryOrThrow(Registries.TRIM_PATTERN)
    val TRUNK_PLACER_TYPE = registryOrThrow(Registries.TRUNK_PLACER_TYPE)
    val VILLAGER_PROFESSION = registryOrThrow(Registries.VILLAGER_PROFESSION)
    val VILLAGER_TYPE = registryOrThrow(Registries.VILLAGER_TYPE)
    val WORLD_PRESET = registryOrThrow(Registries.WORLD_PRESET)
    
    
}