name: Binary Adapter Request
description: Request a new binary adapter.
title: "[Request - BinaryAdapter] "
labels: [ "type: enhancement" ]
body:
  - type: input
    attributes:
      label: Class name
      description: The name of the class you need a binary adapter for.
    validations:
      required: true
