name: Bug Report
description: Create a bug report to help us improve.
labels: [ "type: bug" ]
body:
  - type: checkboxes
    attributes:
      label: Agreements
      options:
        - label: I am using an official build of Nova.
          required: true
        - label: I am running the latest version of Nova.
          required: true
        - label: I am using a [server software supported by Nova](https://docs.xen.cx/nova/compatibility/#compatible-server-software)
          required: true
        - label: I am running the latest version of my server software.
          required: true
        - label: I have checked for similar issues.
          required: true
  - type: dropdown
    id: plugins
    attributes:
      label: Check for plugin incompatibilites
      description: Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin. In order to do that, remove all other plugins from your server and check if the issue still persists. If the issue is caused by another plugin, select "_This issue is about a specific plugin incompatibility_" and state the name, version and where to download that plugin in your report.
      options:
        - There are no other plugins running on my server.
        - This issue is about a specific plugin incompatibility.
    validations:
      required: true
  - type: input
    attributes:
      label: Plugin Version, Server Software, Server Version
      description: "The plugin version, server software and server software version that were used to cause this bug. Use /version to get your server version. If this issue is about a specific plugin incompatibility, also provide the name and version of that plugin."
      placeholder: "Nova: 0.4.1, Spigot: 3241-Spigot-6c1c1b2-1492826 (MC: 1.17.1)"
    validations:
      required: true
  - type: input
    attributes:
      label: Nova Addons and Versions
      description: "Please provide a list of all Nova addons running on your server."
      placeholder: "Logistics v0.1, Machines v0.1, Jetpacks v0.1"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen. Can be left empty if there is no need for an explanation.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Observed/Actual behavior
      description: What you actually saw.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce this behavior. Provide a minimal reproducible example.
      placeholder: "1. Place [...]\n2. Attach [...]\n3. Click on [...] then [...]"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Server log
      description: Upload the complete server log here. Alternatively, you can also upload your log to sites such as [pastebin](https://pastebin.com) or [mclo.gs](https://mclo.gs) and link to it here. __Please always upload your server log, even if you can't see any errors.__
      placeholder: Drag & drop latest.log here
    validations:
      required: true
  - type: textarea
    attributes:
      label: Errors
      description: If any errors or stacktraces appeared in the console, post them here.
      placeholder: Paste error here
      render: log
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
