package xyz.xenondevs.nova.util

import org.bukkit.Material

val Material.burnTime: Int
    get() = FuelUtils.getBurnTime(this)

val Material.fuel: Fuel?
    get() = FuelUtils.getFuel(this)

class Fuel(val material: Material, val burnTime: Int, val remains: Material? = null)

private object FuelUtils {
    
    private val FUELS: Map<Material, Fuel>
    
    init {
        val fuels = listOf(
            Fuel(Material.LAVA_BUCKET, 20000, Material.BUCKET),
            Fuel(Material.COAL_BLOCK, 16000),
            Fuel(Material.BLAZE_ROD, 2400),
            Fuel(Material.COAL, 1600),
            Fuel(Material.CHARCOAL, 1600),
            Fuel(Material.OAK_FENCE, 300),
            Fuel(Material.BIRCH_FENCE, 300),
            Fuel(Material.SPRUCE_FENCE, 300),
            Fuel(Material.JUNGLE_FENCE, 300),
            Fuel(Material.DARK_OAK_FENCE, 300),
            Fuel(Material.ACACIA_FENCE, 300),
            Fuel(Material.OAK_FENCE_GATE, 300),
            Fuel(Material.BIRCH_FENCE_GATE, 300),
            Fuel(Material.SPRUCE_FENCE_GATE, 300),
            Fuel(Material.JUNGLE_FENCE_GATE, 300),
            Fuel(Material.DARK_OAK_FENCE_GATE, 300),
            Fuel(Material.ACACIA_FENCE_GATE, 300),
            Fuel(Material.NOTE_BLOCK, 300),
            Fuel(Material.BOOKSHELF, 300),
            Fuel(Material.LECTERN, 300),
            Fuel(Material.JUKEBOX, 300),
            Fuel(Material.CHEST, 300),
            Fuel(Material.TRAPPED_CHEST, 300),
            Fuel(Material.CRAFTING_TABLE, 300),
            Fuel(Material.DAYLIGHT_DETECTOR, 300),
            Fuel(Material.BOW, 300),
            Fuel(Material.FISHING_ROD, 300),
            Fuel(Material.LADDER, 300),
            Fuel(Material.WOODEN_SHOVEL, 200),
            Fuel(Material.WOODEN_SWORD, 200),
            Fuel(Material.WOODEN_HOE, 200),
            Fuel(Material.WOODEN_AXE, 200),
            Fuel(Material.WOODEN_PICKAXE, 200),
            Fuel(Material.STICK, 100),
            Fuel(Material.BOWL, 100),
            Fuel(Material.DRIED_KELP_BLOCK, 4001),
            Fuel(Material.CROSSBOW, 300),
            Fuel(Material.BAMBOO, 50),
            Fuel(Material.DEAD_BUSH, 100),
            Fuel(Material.SCAFFOLDING, 400),
            Fuel(Material.LOOM, 300),
            Fuel(Material.BARREL, 300),
            Fuel(Material.CARTOGRAPHY_TABLE, 300),
            Fuel(Material.FLETCHING_TABLE, 300),
            Fuel(Material.SMITHING_TABLE, 300),
            Fuel(Material.COMPOSTER, 300),
            Fuel(Material.OAK_PLANKS, 300),
            Fuel(Material.SPRUCE_PLANKS, 300),
            Fuel(Material.BIRCH_PLANKS, 300),
            Fuel(Material.JUNGLE_PLANKS, 300),
            Fuel(Material.ACACIA_PLANKS, 300),
            Fuel(Material.DARK_OAK_PLANKS, 300),
            Fuel(Material.CRIMSON_PLANKS, 300),
            Fuel(Material.WARPED_PLANKS, 300),
            Fuel(Material.OAK_SAPLING, 100),
            Fuel(Material.SPRUCE_SAPLING, 100),
            Fuel(Material.BIRCH_SAPLING, 100),
            Fuel(Material.JUNGLE_SAPLING, 100),
            Fuel(Material.ACACIA_SAPLING, 100),
            Fuel(Material.DARK_OAK_SAPLING, 100),
            Fuel(Material.OAK_LOG, 300),
            Fuel(Material.SPRUCE_LOG, 300),
            Fuel(Material.BIRCH_LOG, 300),
            Fuel(Material.JUNGLE_LOG, 300),
            Fuel(Material.ACACIA_LOG, 300),
            Fuel(Material.DARK_OAK_LOG, 300),
            Fuel(Material.STRIPPED_OAK_LOG, 300),
            Fuel(Material.STRIPPED_SPRUCE_LOG, 300),
            Fuel(Material.STRIPPED_BIRCH_LOG, 300),
            Fuel(Material.STRIPPED_JUNGLE_LOG, 300),
            Fuel(Material.STRIPPED_ACACIA_LOG, 300),
            Fuel(Material.STRIPPED_DARK_OAK_LOG, 300),
            Fuel(Material.WHITE_WOOL, 100),
            Fuel(Material.ORANGE_WOOL, 100),
            Fuel(Material.MAGENTA_WOOL, 100),
            Fuel(Material.LIGHT_BLUE_WOOL, 100),
            Fuel(Material.YELLOW_WOOL, 100),
            Fuel(Material.LIME_WOOL, 100),
            Fuel(Material.PINK_WOOL, 100),
            Fuel(Material.GRAY_WOOL, 100),
            Fuel(Material.LIGHT_GRAY_WOOL, 100),
            Fuel(Material.CYAN_WOOL, 100),
            Fuel(Material.PURPLE_WOOL, 100),
            Fuel(Material.BLUE_WOOL, 100),
            Fuel(Material.BROWN_WOOL, 100),
            Fuel(Material.GREEN_WOOL, 100),
            Fuel(Material.RED_WOOL, 100),
            Fuel(Material.BLACK_WOOL, 100),
            Fuel(Material.OAK_SLAB, 150),
            Fuel(Material.SPRUCE_SLAB, 150),
            Fuel(Material.BIRCH_SLAB, 150),
            Fuel(Material.JUNGLE_SLAB, 150),
            Fuel(Material.ACACIA_SLAB, 150),
            Fuel(Material.DARK_OAK_SLAB, 150),
            Fuel(Material.CRIMSON_SLAB, 150),
            Fuel(Material.WARPED_SLAB, 150),
            Fuel(Material.PETRIFIED_OAK_SLAB, 150),
            Fuel(Material.OAK_STAIRS, 300),
            Fuel(Material.OAK_PRESSURE_PLATE, 300),
            Fuel(Material.SPRUCE_PRESSURE_PLATE, 300),
            Fuel(Material.BIRCH_PRESSURE_PLATE, 300),
            Fuel(Material.JUNGLE_PRESSURE_PLATE, 300),
            Fuel(Material.ACACIA_PRESSURE_PLATE, 300),
            Fuel(Material.DARK_OAK_PRESSURE_PLATE, 300),
            Fuel(Material.CRIMSON_PRESSURE_PLATE, 300),
            Fuel(Material.WARPED_PRESSURE_PLATE, 300),
            Fuel(Material.OAK_TRAPDOOR, 300),
            Fuel(Material.SPRUCE_TRAPDOOR, 300),
            Fuel(Material.BIRCH_TRAPDOOR, 300),
            Fuel(Material.JUNGLE_TRAPDOOR, 300),
            Fuel(Material.ACACIA_TRAPDOOR, 300),
            Fuel(Material.DARK_OAK_TRAPDOOR, 300),
            Fuel(Material.CRIMSON_TRAPDOOR, 300),
            Fuel(Material.WARPED_TRAPDOOR, 300),
            Fuel(Material.SPRUCE_STAIRS, 300),
            Fuel(Material.BIRCH_STAIRS, 300),
            Fuel(Material.JUNGLE_STAIRS, 300),
            Fuel(Material.CRIMSON_STAIRS, 300),
            Fuel(Material.WARPED_STAIRS, 300),
            Fuel(Material.OAK_BUTTON, 100),
            Fuel(Material.SPRUCE_BUTTON, 100),
            Fuel(Material.BIRCH_BUTTON, 100),
            Fuel(Material.JUNGLE_BUTTON, 100),
            Fuel(Material.ACACIA_BUTTON, 100),
            Fuel(Material.DARK_OAK_BUTTON, 100),
            Fuel(Material.CRIMSON_BUTTON, 100),
            Fuel(Material.WARPED_BUTTON, 100),
            Fuel(Material.WHITE_CARPET, 67),
            Fuel(Material.ORANGE_CARPET, 67),
            Fuel(Material.MAGENTA_CARPET, 67),
            Fuel(Material.LIGHT_BLUE_CARPET, 67),
            Fuel(Material.YELLOW_CARPET, 67),
            Fuel(Material.LIME_CARPET, 67),
            Fuel(Material.PINK_CARPET, 67),
            Fuel(Material.GRAY_CARPET, 67),
            Fuel(Material.LIGHT_GRAY_CARPET, 67),
            Fuel(Material.CYAN_CARPET, 67),
            Fuel(Material.PURPLE_CARPET, 67),
            Fuel(Material.BLUE_CARPET, 67),
            Fuel(Material.BROWN_CARPET, 67),
            Fuel(Material.GREEN_CARPET, 67),
            Fuel(Material.RED_CARPET, 67),
            Fuel(Material.BLACK_CARPET, 67),
            Fuel(Material.ACACIA_STAIRS, 300),
            Fuel(Material.DARK_OAK_STAIRS, 300),
            Fuel(Material.OAK_DOOR, 200),
            Fuel(Material.SPRUCE_DOOR, 200),
            Fuel(Material.BIRCH_DOOR, 200),
            Fuel(Material.JUNGLE_DOOR, 200),
            Fuel(Material.ACACIA_DOOR, 200),
            Fuel(Material.DARK_OAK_DOOR, 200),
            Fuel(Material.CRIMSON_DOOR, 200),
            Fuel(Material.WARPED_DOOR, 200),
            Fuel(Material.OAK_SIGN, 200),
            Fuel(Material.SPRUCE_SIGN, 200),
            Fuel(Material.BIRCH_SIGN, 200),
            Fuel(Material.JUNGLE_SIGN, 200),
            Fuel(Material.ACACIA_SIGN, 200),
            Fuel(Material.DARK_OAK_SIGN, 200),
            Fuel(Material.CRIMSON_SIGN, 200),
            Fuel(Material.WARPED_SIGN, 200),
            Fuel(Material.OAK_BOAT, 1200),
            Fuel(Material.WHITE_BANNER, 300),
            Fuel(Material.ORANGE_BANNER, 300),
            Fuel(Material.MAGENTA_BANNER, 300),
            Fuel(Material.LIGHT_BLUE_BANNER, 300),
            Fuel(Material.YELLOW_BANNER, 300),
            Fuel(Material.LIME_BANNER, 300),
            Fuel(Material.PINK_BANNER, 300),
            Fuel(Material.GRAY_BANNER, 300),
            Fuel(Material.LIGHT_GRAY_BANNER, 300),
            Fuel(Material.CYAN_BANNER, 300),
            Fuel(Material.PURPLE_BANNER, 300),
            Fuel(Material.BLUE_BANNER, 300),
            Fuel(Material.BROWN_BANNER, 300),
            Fuel(Material.GREEN_BANNER, 300),
            Fuel(Material.RED_BANNER, 300),
            Fuel(Material.BLACK_BANNER, 300),
            Fuel(Material.SPRUCE_BOAT, 1200),
            Fuel(Material.BIRCH_BOAT, 1200),
            Fuel(Material.JUNGLE_BOAT, 1200),
            Fuel(Material.ACACIA_BOAT, 1200),
            Fuel(Material.DARK_OAK_BOAT, 1200),
        )
        
        FUELS = fuels.map { it.material to it }.toMap()
    }
    
    fun getBurnTime(material: Material) = FUELS[material]?.burnTime ?: 0
    
    fun getFuel(material: Material): Fuel? = FUELS[material]
    
}