package xyz.xenondevs.nova.material

import xyz.xenondevs.nova.material.NovaMaterialRegistry.registerCoreItem

@Suppress("unused")
object CoreGUIMaterial {
    
    val ANVIL_OVERLAY_ARROW = registerCoreItem("gui_anvil_overlay_arrow")
    val ANVIL_OVERLAY_ARROW_LEFT = registerCoreItem("gui_anvil_overlay_arrow_left")
    val ANVIL_OVERLAY_PLUS = registerCoreItem("gui_anvil_overlay_plus")
    val ARROW_1_DOWN = registerCoreItem("gui_arrow_1_down")
    val ARROW_1_LEFT = registerCoreItem("gui_arrow_1_left")
    val ARROW_1_RIGHT = registerCoreItem("gui_arrow_1_right")
    val ARROW_1_UP = registerCoreItem("gui_arrow_1_up")
    val ARROW_2_DOWN = registerCoreItem("gui_arrow_2_down")
    val ARROW_2_LEFT = registerCoreItem("gui_arrow_2_left")
    val ARROW_2_RIGHT = registerCoreItem("gui_arrow_2_right")
    val ARROW_2_UP = registerCoreItem("gui_arrow_2_up")
    val CHECKMARK = registerCoreItem("gui_checkmark")
    val CORNER_BOTTOM_LEFT = registerCoreItem("gui_corner_bottom_left")
    val CORNER_BOTTOM_RIGHT = registerCoreItem("gui_corner_bottom_right")
    val CORNER_TOP_LEFT = registerCoreItem("gui_corner_top_left")
    val CORNER_TOP_RIGHT = registerCoreItem("gui_corner_top_right")
    val GREEN_CHECKMARK = registerCoreItem("gui_green_checkmark")
    val HORIZONTAL_DOTS = registerCoreItem("gui_horizontal_dots")
    val HORIZONTAL_DOWN = registerCoreItem("gui_horizontal_down")
    val HORIZONTAL_LINE = registerCoreItem("gui_horizontal_line")
    val HORIZONTAL_UP = registerCoreItem("gui_horizontal_up")
    val INVENTORY_PART = registerCoreItem("gui_inventory_part")
    val INVISIBLE_ITEM = registerCoreItem("gui_invisible")
    val LIGHT_ARROW_1_DOWN = registerCoreItem("gui_light_arrow_1_down")
    val LIGHT_ARROW_1_LEFT = registerCoreItem("gui_light_arrow_1_left")
    val LIGHT_ARROW_1_RIGHT = registerCoreItem("gui_light_arrow_1_right")
    val LIGHT_ARROW_1_UP = registerCoreItem("gui_light_arrow_1_up")
    val LIGHT_ARROW_2_DOWN = registerCoreItem("gui_light_arrow_2_down")
    val LIGHT_ARROW_2_LEFT = registerCoreItem("gui_light_arrow_2_left")
    val LIGHT_ARROW_2_RIGHT = registerCoreItem("gui_light_arrow_2_right")
    val LIGHT_ARROW_2_UP = registerCoreItem("gui_light_arrow_2_up")
    val LIGHT_CHECKMARK = registerCoreItem("gui_light_checkmark")
    val LIGHT_CORNER_BOTTOM_LEFT = registerCoreItem("gui_light_corner_bottom_left")
    val LIGHT_CORNER_BOTTOM_RIGHT = registerCoreItem("gui_light_corner_bottom_right")
    val LIGHT_CORNER_TOP_LEFT = registerCoreItem("gui_light_corner_top_left")
    val LIGHT_CORNER_TOP_RIGHT = registerCoreItem("gui_light_corner_top_right")
    val LIGHT_HORIZONTAL_DOTS = registerCoreItem("gui_light_horizontal_dots")
    val LIGHT_HORIZONTAL_DOWN = registerCoreItem("gui_light_horizontal_down")
    val LIGHT_HORIZONTAL_LINE = registerCoreItem("gui_light_horizontal_line")
    val LIGHT_HORIZONTAL_UP = registerCoreItem("gui_light_horizontal_up")
    val LIGHT_VERTICAL_DOTS = registerCoreItem("gui_light_vertical_dots")
    val LIGHT_VERTICAL_HORIZONTAL = registerCoreItem("gui_light_vertical_horizontal")
    val LIGHT_VERTICAL_LEFT = registerCoreItem("gui_light_vertical_left")
    val LIGHT_VERTICAL_LINE = registerCoreItem("gui_light_vertical_line")
    val LIGHT_VERTICAL_RIGHT = registerCoreItem("gui_light_vertical_right")
    val LIGHT_X = registerCoreItem("gui_light_x")
    val RED_X = registerCoreItem("gui_red_x")
    val VERTICAL_DOTS = registerCoreItem("gui_vertical_dots")
    val VERTICAL_HORIZONTAL = registerCoreItem("gui_vertical_horizontal")
    val VERTICAL_LEFT = registerCoreItem("gui_vertical_left")
    val VERTICAL_LINE = registerCoreItem("gui_vertical_line")
    val VERTICAL_RIGHT = registerCoreItem("gui_vertical_right")
    val X = registerCoreItem("gui_x")
    val AREA_BTN_OFF = registerCoreItem("gui_area_btn_off", "menu.nova.visual_region.show")
    val AREA_BTN_ON = registerCoreItem("gui_area_btn_on", "menu.nova.visual_region.hide")
    val MINUS_BTN_OFF = registerCoreItem("gui_minus_btn_off")
    val MINUS_BTN_ON = registerCoreItem("gui_minus_btn_on")
    val PLUS_BTN_OFF = registerCoreItem("gui_plus_btn_off")
    val PLUS_BTN_ON = registerCoreItem("gui_plus_btn_on")
    val SIDE_CONFIG_BTN = registerCoreItem("gui_side_config_btn", "menu.nova.side_config")
    val ENERGY_BTN_OFF = registerCoreItem("gui_energy_btn_off")
    val ENERGY_BTN_ON = registerCoreItem("gui_energy_btn_on")
    val ENERGY_BTN_SELECTED = registerCoreItem("gui_energy_btn_selected")
    val ITEM_BTN_OFF = registerCoreItem("gui_items_btn_off")
    val ITEM_BTN_ON = registerCoreItem("gui_items_btn_on")
    val ITEM_BTN_SELECTED = registerCoreItem("gui_items_btn_selected")
    val FLUID_BTN_OFF = registerCoreItem("gui_fluids_btn_off")
    val FLUID_BTN_ON = registerCoreItem("gui_fluids_btn_on")
    val FLUID_BTN_SELECTED = registerCoreItem("gui_fluids_btn_selected")
    val BLUE_BTN = registerCoreItem("gui_blue_btn")
    val GRAY_BTN = registerCoreItem("gui_gray_btn")
    val GREEN_BTN = registerCoreItem("gui_green_btn")
    val ORANGE_BTN = registerCoreItem("gui_orange_btn")
    val PINK_BTN = registerCoreItem("gui_pink_btn")
    val RED_BTN = registerCoreItem("gui_red_btn")
    val WHITE_BTN = registerCoreItem("gui_white_btn")
    val YELLOW_BTN = registerCoreItem("gui_yellow_btn")
    val BAR_BLUE = registerCoreItem("gui_bar_blue")
    val BAR_GREEN = registerCoreItem("gui_bar_green")
    val BAR_RED = registerCoreItem("gui_bar_red")
    val BAR_ORANGE = registerCoreItem("gui_bar_orange")
    val TP_BAR_BLUE = registerCoreItem("gui_tp_bar_blue")
    val TP_BAR_GREEN = registerCoreItem("gui_tp_bar_green")
    val TP_BAR_RED = registerCoreItem("gui_tp_bar_red")
    val TP_BAR_ORANGE = registerCoreItem("gui_tp_bar_orange")
    val NUMBER = registerCoreItem("gui_number")
    val MINUS = registerCoreItem("gui_minus")
    val TP_SEARCH = registerCoreItem("gui_tp_search")
    val TP_ARROW_LEFT_BTN_OFF = registerCoreItem("gui_tp_arrow_left_btn_off")
    val TP_ARROW_LEFT_BTN_ON = registerCoreItem("gui_tp_arrow_left_btn_on")
    val TP_ARROW_RIGHT_BTN_OFF = registerCoreItem("gui_tp_arrow_right_btn_off")
    val TP_ARROW_RIGHT_BTN_ON = registerCoreItem("gui_tp_arrow_right_btn_on")
    val TP_STOPWATCH = registerCoreItem("gui_tp_stopwatch")
    val TP_COLOR_PICKER = registerCoreItem("gui_tp_color_picker")
    val TP_PIXEL_ARROW_LEFT_OFF = registerCoreItem("gui_tp_pixel_arrow_left_off")
    val TP_PIXEL_ARROW_LEFT_ON = registerCoreItem("gui_tp_pixel_arrow_left_on")
    val TP_PIXEL_ARROW_RIGHT_OFF = registerCoreItem("gui_tp_pixel_arrow_right_off")
    val TP_PIXEL_ARROW_RIGHT_ON = registerCoreItem("gui_tp_pixel_arrow_right_on")
    
    // Might be moved to a separate addon in the future
    val UPGRADES_BTN = registerCoreItem("gui_upgrades_btn", "menu.nova.upgrades")
    val SPEED_UPGRADE = registerCoreItem("gui_speed_upgrade")
    val EFFICIENCY_UPGRADE = registerCoreItem("gui_efficiency_upgrade")
    val ENERGY_UPGRADE = registerCoreItem("gui_energy_upgrade")
    val RANGE_UPGRADE = registerCoreItem("gui_range_upgrade")
    val FLUID_UPGRADE = registerCoreItem("gui_fluid_upgrade")
    
}